### ISSUE TITLE
[EPIC] Gophercloud V2 Migration 

### ISSUE THREAD

**Issue by Sharpz7** [openstack-exporter/openstack-exporter#385]
https://github.com/gophercloud/gophercloud/blob/master/docs/MIGRATING.md

This has already been lightly covered in https://github.com/openstack-exporter/openstack-exporter/issues/381, but this ticket will track step-by-step changes I am working on to get to a fully migrated openstack-exporter.

- [ ] https://github.com/openstack-exporter/openstack-exporter/issues/377 - this will include the bare-minimum migration changes required to get this PR to be functional
- [ ] Work on V2 Migration for all Ironic API's
- [ ] Other Migration work (Order to be decided)
